version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      maven:
        patterns:
          - "*"
    ignore:
      - dependency-name:
          - "com.hierynomus:smbj"
          - "com.rapid7.client:dcerpc"
          - "de.psdev.licensesdialog:licensesdialog"