version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Action: "
    groups:
      ci-actions:
        patterns: ["*"]
      
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Build: "
    ignore:
      - dependency-name: "com.github.bitfireAT:dav4jvm"
      - dependency-name: "com.hierynomus:smbj"
      - dependency-name: "de.psdev.licensesdialog:licensesdialog"
      - dependency-name: "com.google.android.material:material"
    groups:
      app-dependencies:
        patterns: ["*"]
