version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    groups:
      maven:
        patterns:
          - "*"
    ignore:
      - dependency-name: "com.hierynomus:smbj"
      - dependency-name: "com.rapid7.client:dcerpc"
      - dependency-name: "de.psdev.licensesdialog:licensesdialog"