name: Android CI

on:
  workflow_dispatch:
  push:
    branches: master
    tags:
  pull_request:
  merge_group:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Build with Gradle
      run: ./gradlew assembleDebug lintVitalRelease
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 10
